### ISSUE TITLE
Switch Auth / Social Media integration to Twitter

### ISSUE THREAD

**Issue by hgzimmerman** [hgzimmerman/SWEN344-web-project#119]
Facebook doesn't work very well.

**Comment by hgzimmerman** [comment]
I'm calling this done. I'm reasonably confident that there aren't any bugs in the backend implementation at this point.

**Comment by hgzimmerman** [comment]
I'm an idiot, no one has implemented the social media functionality on the frontend, which falls under the scope of this issue. Reopening.

**Comment by dxf7606** [comment]
I'm working on it!

**Comment by hgzimmerman** [comment]
This works well enough to satisfy requirements. via https://github.com/hgzimmerman/SWEN344-web-project/pull/179
