### ISSUE TITLE
Determine stock trading API 

### ISSUE THREAD

**Issue by hgzimmerman** [hgzimmerman/SWEN344-web-project#33]
What stock trading api do we want to use?
https://iextrading.com/developer/docs/ looks nice.

**Comment by hgzimmerman** [comment]
https://www.quora.com/Did-Yahoo-Stock-API-shut-down yahoo is shut down

**Comment by hgzimmerman** [comment]
IEX for now.

**Comment by beltrancaliz** [comment]
Using iextrading
